apiVersion: apps/v1
kind: Deployment
metadata:
  name:  creditrisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creditriskpredictor
  template:
    metadata:
      labels:
        app: creditriskpredictor
    spec:
      containers:
      - name: cv-app
        image: gcr.io/mlops-358310/mlopswebapp:v1
        ports:
        - containerPort: 8501